config/routes.rb
Rails.application.routes.draw do
  get 'alerts/show'

  get 'getting-started' => 'onboarding#index'
  get 'dashboard' => 'dashboard#index'
  get 'pay-what-you-want' => 'payments#new'
  post 'payments' => 'payments#create'
  get 'subscription' => 'payments#show'
  delete 'payments' => 'payments#destroy'
  get 'start' => 'registrations#sign_up'

  post 'toys' => 'toys#search'

  resources :children, only: [:create] do
    resources :toys, on: :member
    resources :alerts, on: :member do
      post 'setup_demo', on: :collection
    end
  end

  resources :alerts, only: [:destroy]

  namespace 'api' do
    get 'gender/guess' => 'gender#guess'
    put 'volatile_session/store' => 'volatile_session#store'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations',
  },
    path: 'account',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'start',
    }

  mount Split::Dashboard, :at => 'split'

  resources :blog, only: [ :index, :show ]

  get 'about' => 'site#about'
  get 'how-it-works' => 'site#how_it_works'

  root 'site#index'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :child
  belongs_to :report, class_name: 'ToyReport'
  has_one :toy, through: :report

  validates :child_id, :report_id, presence: true

  delegate :parent, to: :child

  after_create :send_email

  def acknowledged?
    !!acknowledged_on
  end

  def send_email
  	TransactionMailer.alert(parent, child).deliver
  end
end

app/models/child.rb
class Child < ActiveRecord::Base
  include FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :parent, class_name: 'User'
  has_many :toy_ownerships, dependent: :destroy
  has_many :toys, through: :toy_ownerships
  has_many :alerts, -> { order 'acknowledged_on ASC' }, dependent: :destroy
  has_many :unacknowledged_alerts, -> { where 'acknowledged_on IS NULL' }, class_name: 'Alert', dependent: :destroy
  has_many :acknowledged_alerts, -> { where 'acknowledged_on IS NOT NULL' }, class_name: 'Alert', dependent: :destroy

  sync :all
  sync_scope :by_parent, -> (parent) { where(parent_id: parent.id) }

  validates :name, :parent_id, presence: true

  delegate :first_name, :last_name, to: :parent, prefix: true

  def pronoun
    case gender
    when 'female'; 'her'
    when 'male'; 'his'
    else
      'their'
    end
  end

  def slug_candidates
    [
      :name,
      [ :name, :parent_first_name ],
      [ :name, :parent_first_name, :parent_last_name ],
      [ :name, :parent_last_name ],
      [ :name, :parent_last_name, :parent_first_name ],
      [ :name, :parent_first_name, :parent_id ],
    ]
  end
end

app/models/test_resource.rb
class TestResource < ActiveRecord::Base
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  has_many :reports, class_name: 'ToyReport'

  validates :name, presence: true

  serialize :descriptions, Array

  def self.search_one(upc)
    toy = Toy.where(upc: upc).first
    return toy if toy

    toys = ToySearchService.search(upc)
    toys.each {|toy| toy.save }
    toys.first
  end
end

app/models/toy_ownership.rb
class ToyOwnership < ActiveRecord::Base
  belongs_to :toy
  belongs_to :child

  sync :all
  sync_scope :by_child, -> (child) { where(child_id: child.id) }

  delegate :parent_id, to: :child, prefix: false

  after_save :create_alerts

  def create_alerts
    if toy.reports.any?
      toy.reports.each do |report|
        child.alerts.create!(
          report: report,
        )
      end
    end
  end
end

app/models/toy_report.rb
class ToyReport < ActiveRecord::Base
  belongs_to :toy

  serialize :remedy_types, Array
end

app/models/user.rb
class User < ActiveRecord::Base
  include NewsletterSubscribable

  has_many :children, foreign_key: :parent_id, dependent: :destroy
  has_many :toys, through: :children
  has_many :authentications, class_name: 'UserAuthentication', dependent: :destroy
  has_many :alerts, through: :children
  has_many :acknowledged_alerts, through: :children
  has_many :unacknowledged_alerts, through: :children

  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  validates :email, uniqueness: { case_sensitive: false }

  after_create :send_email

  def self.create_from_omniauth(params)
    attributes = {
      email: params['info']['email'],
      first_name: params['info']['first_name'],
      last_name: params['info']['last_name'],
      image: params['info']['image'],
      password: Devise.friendly_token
    }

    create(attributes)
  end

  def send_email
    TransactionMailer.welcome(self).deliver
  end
end

app/models/user_authentication.rb
class UserAuthentication < ActiveRecord::Base
  belongs_to :user
  belongs_to :authentication_provider

  serialize :params

  def self.create_from_omniauth(params, user, provider)
    token_expires_at = params['credentials']['expires_at'] ? Time.at(params['credentials']['expires_at']).to_datetime : nil

    create(
      user: user,
      authentication_provider: provider,
      uid: params['uid'],
      token: params['credentials']['token'],
      token_expires_at: token_expires_at,
      params: params,
    )
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  layout 'landing'
  
  def index
  end

  def show
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'landing'

  def index
    @header_ab_test = ab_test('header',
      "Alerts when your kids’ toys become safety hazards",
      "Free alerts when your kids’ toys become safety hazards"
    )

    @page_title = "Free alerts when your kids toys' become safety hazards"
  end

  def about
  end

  def how_it_works
    if current_user
      @child = current_user.children.try(:first) || Child.new
      @email = current_user.email
    else
      @child = Child.new(name: session[:child_name])
      @email = session[:email]
    end

    @child.toys = [
      Toy.new(name: 'Toy 1'),
    ]

    @page_title = "How to keep children safe from dangerous toys"

    @skip_footer = true
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(name, options, html_options = {})
    html_options[:wrap_tag] = 'li'
    html_options[:active] = :exclusive
    super(name, options, html_options)
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/onboarding_helper.rb
module OnboardingHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/toy_helper.rb
module ToyHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/shared/_add_child_form.html.slim
.row
  .col-md-6.info
    h4 First, tell us a little bit about your kids!

    p
      | (bragging allowed; we love knowing about the kids we help!)
    
    h4 What is this for?

    p
      | We use your children's names to help you locate a faulty toy when the moment's right, so that we are able to help you know whose room to check.

  .col-md-6
    .form#new-child
      = form_for @child, remote: true do |f|
        .row
          .col-md-6
            .form-group
              = f.text_field :name, class: 'form-control', autofocus: true, placeholder: "Your child's first name"

        .row
          .col-md-6
            .form-group
              = f.text_field :birthday, class: 'form-control', placeholder: "Birthday MM/DD/YYYY"
              span.note This is an optional field

        .row
          .col-md-6
            .form-group
              = f.radio_button :gender, :female
              label.female[for="child_gender_female"]
                span.fa.fa-venus
                |  Girl
            .form-group
              = f.radio_button :gender, :male
              label.male[for="child_gender_male"]
                span.fa.fa-mars
                |  Boy

app/views/shared/_add_toy_form.html.slim
#new-toy.modal.fade.transparent
  = form_tag '', id: 'new_toy', remote: true do |f|
    .modal-dialog.modal-lg
      .modal-content
        h2
          | Select a few toys to kickstart 
          span[data-role="child-name"] Karen
          | 's toylist
        h4
          | (don't worry, you'll be able to change this later)

        .row.search
          input#search.col-md-10[type="text" placeholder="Search by toy name, manufacturer of bar code"]
          a.btn.btn-primary#search-btn[href="#"]
            span.fa.fa-search
          p.suggestions
            | e.g.: 
            a[href='#'] My Little Pony
            | , 
            a[href='#'] Mattel
            | , 
            a[href='#'] 045496742508


        .row.toylist.list.isotope#suggestions
          - @toy_suggestions.each do |gender, toys|
            - toys.each do |toy|
              = hidden_field_tag "toys[#{toy.id}]", "false"
              a.isotope-item[href='#' data-toyid=toy.id class=gender]
                span.image
                  img[src=toy.image]
                span.toy-name= toy.name

        .row.toylist.list.isotope#search-results

      .modal-footer
        a.btn.btn-outline[href='#' data-dismiss="modal"] Cancel
        a.btn.btn-outline[href='#' data-role="submit"] Continue

app/views/shared/_facebook_signup_button.html.slim
a.btn.btn-social.btn-facebook[href= user_omniauth_authorize_path(:facebook)]
  i.fa.fa-facebook
  | Sign in with Facebook

app/views/shared/_footer.html.slim
.container
  .row
    .col-sm-3.copyright
      | RecallBee LLC #{Date.today.year}
    .col-sm-6.menu
      ul
        li
          a[href=blog_index_path]
            | Blog

app/views/shared/_header.html.slim
 .navbar-header
  button.navbar-toggle[type="button" data-toggle="collapse" data-target=".bs-navbar-collapse"]
    span.icon-bar
    span.icon-bar
    span.icon-bar
  a.navbar-brand[href=dashboard_path]
    = image_tag 'logo-white.png'

app/views/shared/_mixpanel.html.erb
<script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("<%= Rails.application.secrets.mixpanel_token %>");
<%- if @mixpanel_identity %>
  mixpanel.identify("<%= @mixpanel_identity %>");
<% end %>
mixpanel.track('page view', {
  url: window.location.pathname
})
</script>

app/views/shared/_navigation.html.slim
ul.nav.navbar-nav
  = active_link_to 'Dashboard', dashboard_path
  = active_link_to 'Blog', blog_index_path
ul.nav.navbar-nav.navbar-right.visible-md.visible-lg
  li
    a.btn.btn-primary[href=edit_user_registration_path] My Account

app/views/shared/_twitter_signup_button.html.slim
a.btn.btn-social.btn-twitter[href= user_omniauth_authorize_path(:twitter)]
  i.fa.fa-twitter
  | Sign in with Twitter

app/views/shared/landing/_footer.html.slim
.container
  .row
    .col-sm-12.text-center.bottom-separator
      img.img-responsive.inline[src=image_path("triangle/home/under.png")]
    .col-md-3.col-sm-6
    .col-md-3.col-sm-6
      .contact-info.bottom
        h2
          | Social Networks
        a.twitter-follow-button[href="https://twitter.com/RecallBee" data-show-count="false" data-size="large" data-dnt="true"]
          | Follow @RecallBee
        script
          | !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
        a.btn.btn-social.btn-facebook[href="http://www.facebook.com/RecallBeeApp"]
          i.fa.fa-facebook
          | RecallBee on Facebook

        #fb-root
        script
          | (function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1603868103162053&version=v2.0"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));
        .fb-like[data-href="http://www.recallbee.com/" data-width="250" data-layout="button" data-action="like" data-show-faces="true" data-share="true"]
    .col-md-5.col-sm-12
      .contact-form.bottom
        h2 Subscribe to our high-value newsletter
        form[action="http://linkedin.us9.list-manage.com/subscribe/post?u=565ed18634426e342ea4b57e5&id=986c8b4b57" method="post" target="_blank"]
          .row
            .col-md-5
              input.form-control[type="text" name="FNAME" placeholder="First Name"]
            .col-md-5
              input.col-md-4.form-control[type="text" name="LNAME" placeholder="Last Name"]
          .row
            .col-md-10
              input.form-control[type="email" name="EMAIL" placeholder="Email"]
          .row
            .col-md-10
              button.btn.btn-success.btn-fullsize.btn-lg[type="submit"] Get practical safety tips!
    .col-sm-12
      .copyright-text.text-center
        p © RecallBee #{Date.today.year}. All Rights Reserved.

app/views/shared/landing/_navigation.html.slim
- unless current_user
  .nav= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-register'

ul.nav.navbar-nav.navbar-right
  = active_link_to 'Home', '/'
  = active_link_to 'How It Works', how_it_works_path
  = active_link_to 'Pricing', pay_what_you_want_path
  - if current_user
    = active_link_to 'Dashboard', dashboard_path

app/views/shared/landing/_social.html.slim
.container
  .row
    .col-sm-12.overflow
      .social-icons.pull-right
        ul.nav.nav-pills
          li
            a[href="https://www.facebook.com/RecallBeeApp"]
              i.fa.fa-facebook
          li
            a[href=""]
              i.fa.fa-twitter

app/views/shared/landing/_stats.html.slim
section.full-hero
  .vertical-center
    .container
      .row
        .action.stats
          .col-sm-3.text-center.wow.bounceIn.animated[data-wow-duration="1000ms" data-wow-delay="300ms" style="visibility: visible; -webkit-animation-duration: 1000ms; -webkit-animation-delay: 300ms;"]
            h1.bold
              = number_with_delimiter @days_since_starting_operations
            h3
              | Days Monitoring Toys
          .col-sm-3.text-center.wow.bounceIn.animated[data-wow-duration="1000ms" data-wow-delay="300ms" style="visibility: visible; -webkit-animation-duration: 1000ms; -webkit-animation-delay: 300ms;"]
            h1.bold
              = number_with_delimiter @alerts_sent
            h3
              | Alerts Sent
          .col-sm-3.text-center.wow.bounceIn.animated[data-wow-duration="1000ms" data-wow-delay="300ms" style="visibility: visible; -webkit-animation-duration: 1000ms; -webkit-animation-delay: 300ms;"]
            h1.bold
              = number_with_delimiter @toys_monitored
            h3
              | Toys Being Monitored
          .col-sm-3.text-center.wow.bounceIn.animated[data-wow-duration="1000ms" data-wow-delay="300ms" style="visibility: visible; -webkit-animation-duration: 1000ms; -webkit-animation-delay: 300ms;"]
            h1.bold
              = number_with_delimiter @customers
            h3
              | Parents We Are Helping