config/routes.rb
Rails.application.routes.draw do
  get 'alerts/show'

  get 'getting-started' => 'onboarding#index'
  get 'dashboard' => 'dashboard#index'
  get 'pay-what-you-want' => 'payments#new'
  post 'payments' => 'payments#create'
  get 'subscription' => 'payments#show'
  delete 'payments' => 'payments#destroy'
  get 'start' => 'registrations#sign_up'

  post 'toys' => 'toys#search'

  resources :children, only: [:create] do
    resources :toys, on: :member
    resources :alerts, on: :member do
      post 'setup_demo', on: :collection
    end
  end

  resources :alerts, only: [:destroy]

  namespace 'api' do
    get 'gender/guess' => 'gender#guess'
    put 'volatile_session/store' => 'volatile_session#store'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations',
  },
    path: 'account',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'start',
    }

  mount Split::Dashboard, :at => 'split'

  resources :blog, only: [ :index, :show ]

  get 'about' => 'site#about'
  get 'how-it-works' => 'site#how_it_works'

  root 'site#index'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :child
  belongs_to :report, class_name: 'ToyReport'
  has_one :toy, through: :report

  validates :child_id, :report_id, presence: true

  delegate :parent, to: :child

  after_create :send_email

  def acknowledged?
    !!acknowledged_on
  end

  def send_email
  	TransactionMailer.alert(parent, child).deliver
  end
end

app/models/child.rb
class Child < ActiveRecord::Base
  include FriendlyId
  friendly_id :slug_candidates, use: :slugged

  belongs_to :parent, class_name: 'User'
  has_many :toy_ownerships, dependent: :destroy
  has_many :toys, through: :toy_ownerships
  has_many :alerts, -> { order 'acknowledged_on ASC' }, dependent: :destroy
  has_many :unacknowledged_alerts, -> { where 'acknowledged_on IS NULL' }, class_name: 'Alert', dependent: :destroy
  has_many :acknowledged_alerts, -> { where 'acknowledged_on IS NOT NULL' }, class_name: 'Alert', dependent: :destroy

  sync :all
  sync_scope :by_parent, -> (parent) { where(parent_id: parent.id) }

  validates :name, :parent_id, presence: true

  delegate :first_name, :last_name, to: :parent, prefix: true

  def pronoun
    case gender
    when 'female'; 'her'
    when 'male'; 'his'
    else
      'their'
    end
  end

  def slug_candidates
    [
      :name,
      [ :name, :parent_first_name ],
      [ :name, :parent_first_name, :parent_last_name ],
      [ :name, :parent_last_name ],
      [ :name, :parent_last_name, :parent_first_name ],
      [ :name, :parent_first_name, :parent_id ],
    ]
  end
end

app/models/test_resource.rb
class TestResource < ActiveRecord::Base
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  has_many :reports, class_name: 'ToyReport'

  validates :name, presence: true

  serialize :descriptions, Array

  def self.search_one(upc)
    toy = Toy.where(upc: upc).first
    return toy if toy

    toys = ToySearchService.search(upc)
    toys.each {|toy| toy.save }
    toys.first
  end
end

app/models/toy_ownership.rb
class ToyOwnership < ActiveRecord::Base
  belongs_to :toy
  belongs_to :child

  sync :all
  sync_scope :by_child, -> (child) { where(child_id: child.id) }

  delegate :parent_id, to: :child, prefix: false

  after_save :create_alerts

  def create_alerts
    if toy.reports.any?
      toy.reports.each do |report|
        child.alerts.create!(
          report: report,
        )
      end
    end
  end
end

app/models/toy_report.rb
class ToyReport < ActiveRecord::Base
  belongs_to :toy

  serialize :remedy_types, Array
end

app/models/user.rb
class User < ActiveRecord::Base
  include NewsletterSubscribable

  has_many :children, foreign_key: :parent_id, dependent: :destroy
  has_many :toys, through: :children
  has_many :authentications, class_name: 'UserAuthentication', dependent: :destroy
  has_many :alerts, through: :children
  has_many :acknowledged_alerts, through: :children
  has_many :unacknowledged_alerts, through: :children

  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  validates :email, uniqueness: { case_sensitive: false }

  after_create :send_email

  def self.create_from_omniauth(params)
    attributes = {
      email: params['info']['email'],
      first_name: params['info']['first_name'],
      last_name: params['info']['last_name'],
      image: params['info']['image'],
      password: Devise.friendly_token
    }

    create(attributes)
  end

  def send_email
    TransactionMailer.welcome(self).deliver
  end
end

app/models/user_authentication.rb
class UserAuthentication < ActiveRecord::Base
  belongs_to :user
  belongs_to :authentication_provider

  serialize :params

  def self.create_from_omniauth(params, user, provider)
    token_expires_at = params['credentials']['expires_at'] ? Time.at(params['credentials']['expires_at']).to_datetime : nil

    create(
      user: user,
      authentication_provider: provider,
      uid: params['uid'],
      token: params['credentials']['token'],
      token_expires_at: token_expires_at,
      params: params,
    )
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  layout 'landing'
  
  def index
  end

  def show
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  layout :layout

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripe_token][:id],
      plan: params[:plan],
      email: params[:stripe_token][:email],
    )

    current_user.update_attributes!(
      stripe_token: customer.id
    )

    head :ok
  end

  def show
    return if current_user.stripe_token.blank?

    stripe_customer = Stripe::Customer.retrieve(current_user.stripe_token)
    @stripe_subscription = stripe_customer.subscriptions.all.data[0]
  end

  def destroy
    return if current_user.stripe_token.blank?

    stripe_customer = Stripe::Customer.retrieve(current_user.stripe_token)
    stripe_customer.subscriptions.first.delete

  ensure
    redirect_to subscription_path
  end

  protected

  def layout
    if current_user
      'application'
    else
      'landing'
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'landing'

  def index
    @header_ab_test = ab_test('header',
      "Alerts when your kids’ toys become safety hazards",
      "Free alerts when your kids’ toys become safety hazards"
    )

    @page_title = "Free alerts when your kids toys' become safety hazards"
  end

  def about
  end

  def how_it_works
    if current_user
      @child = current_user.children.try(:first) || Child.new
      @email = current_user.email
    else
      @child = Child.new(name: session[:child_name])
      @email = session[:email]
    end

    @child.toys = [
      Toy.new(name: 'Toy 1'),
    ]

    @page_title = "How to keep children safe from dangerous toys"

    @skip_footer = true
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_filter :load_resources, except: [:search]

  def index
    @toys = @child.toys
  end

  def create
    params[:toys].each do |toy_id, boolean|
      if boolean == 'true'
        toy_ownership = @child.toy_ownerships.new(
          toy_id: toy_id,
        )

        authorize toy_ownership
        toy_ownership.save!
      end
    end

    head :no_content
  end

  def search
    @toys = ToySearchService.search(params[:q], 'All')

    render json: @toys
  end

  private

  def load_resources
    @child = Child.where(slug: params[:child_id]).first!
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link_to(name, options, html_options = {})
    html_options[:wrap_tag] = 'li'
    html_options[:active] = :exclusive
    super(name, options, html_options)
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/onboarding_helper.rb
module OnboardingHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/toy_helper.rb
module ToyHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/payments/_form.html.slim
= form_tag do
  = hidden_field_tag 'user_email', current_user.try(:email)
  = hidden_field_tag 'stripe_key', Rails.application.secrets.stripe_api_public
  <script src="https://checkout.stripe.com/checkout.js"></script>
  p.form
    span I believe 
    select#amount-of-subscription[name="plan"]
      option[value="2.50-mo"] $2.50/mo
      option[value="5-mo"] $5/mo
      option[value="10-mo" selected="selected"] $10/mo
      option[value="15-mo"] $15/mo
      option[value="20-mo"] $20/mo
      option[value="25-mo"] $25/mo
      option[value="30-mo"] $30/mo
      option[value="50-mo"] $50/mo
      option[value="100-mo"] $100/mo
    span  is a fair price.

p
  a.btn.btn-success#stripe-subscribe-button[href="#"]
    i.fa.fa-lock
    |  Help keep kids safe
p
  span.note
    | * You can stop this subscription at any time.

app/views/payments/create.html.slim
h1 Payments#create
p Find me in app/views/payments/create.html.slim

app/views/payments/new.html.slim
section.payments
  .container
    .row.header
      .col-md-12
        h2
          | How much is worth the safety RecallBee provides to 
          b
            u you
          | ?
        p RecallBee uses a friendly pay-what-you-want pricing model

    .row.feature.hidden
      .col-md-5.col-md-offset-1.info.text-justify
        h4 We want everyone to be able to afford RecallBee
        p
          | If a family is struggling and not able to support our mission 
          | to keep families safe we still want them to be able to benefit 
          | from it.

      .col-md-2.image
        = image_tag 'recycle-icon.png'

    .row.form
      .col-md-2.col-md-offset-1
        = image_tag 'woman-icon.png'

      .col-md-7.text-center.form
        = render partial: 'form'

  = render partial: 'shared/landing/stats'

  .container
    .row.feature
      .col-md-5.col-md-offset-1.info.text-justify
        h4 We were shocked

        p
          | when we discovered 
          | just how many toys, kids' furniture, cribs and apparel are silently recalled (and even worse, 
          i not
          |  recalled) throughout the year.

      .col-md-5.info.text-justify
        h4 We decided to do something about it

        p.text-justify
          | We created a tool that 
          | bridges the gap between safety reports and parents, 
          | making sure that they would know when their children 
          | might be exposed to hazardous toys.

      .col-md-12.hidden

        .row
          .col-md-8
            .row
              .col-md-4
              .col-md-8
                p.text-justify
                  | We were shocked when we discovered 
                  | just how many toys and kids' furniture, cribs and apparel are silently recalled (and even worse, 
                  i not
                  |  recalled)

                h3 

                

            .row
              .col-md-4
                = image_tag 'recycle-icon.png'
              .col-md-8
                h3
                  | 

                

                h4
                  | If you are able to support our mission, here's your chance 
                  | to do it. 
                h3 Most parents give in the range of $9-$10/month.
        .col-md-4
          h3 Contributing

app/views/payments/show.slim
section.payments
  .container
    .row.header
      .col-md-12
        h2
          | How much is worth the safety RecallBee provides to 
          b
            u you
          | ?
        p RecallBee uses a friendly pay-what-you-want pricing model

    .row.form
      .col-md-2.col-md-offset-1
        = image_tag 'woman-icon.png'

      .col-md-7.text-center.form
        - if @stripe_subscription
          h3
            | Thanks!

          h4
            | You are supporting the cause of 
            | keeping kids safe from faulty toys on the #{@stripe_subscription.plan.name} level.

          p
            = link_to "You can cancel this support at any time.", payments_path, method: 'delete', confirm: "This will cancel your support for RecallBee's mission to keep kids safe from faulty toys, are you sure you want to do that now?"
        - else
          p You don't currently have any active subscriptions

          = render partial: 'form'